void main(List<String> args) {
  String ilce = "Gönen";
  String kita = "Asya";
  String faks = "+902667623337";
  String postaKodu = "10680";
  String instaAdresi = "https://www.instagram.com/tumerkan_karabel/";
  String calistiginBolum = "Yazılım";
  int urunMiktari = 1500;
  String musteriSoyadi = "Karabel";
  double odemeMiktari = 7500;
  String dogumTarihi = "03.02.1998";
  double borc = 2500;
  String medeniHal = "bekar";
  String videoYorumu = "Cok güzel video, elinize sağlık";
  String odemeSaati = "11:50";
  double eftMiktari = 1500;
  double satilanMiktar = 15000;
  String telefonModeli = "Iphone 15 Pro";
  String dergiAdi = "Socrates";
  String basimTarihi = "11.05.2020";
  double zamMiktari = 300;
  int daireSayisi = 5;
  double enlem = 48.8583701;
  double boylam = 2.2919064;
  String yemekAdi = "Kremalı Mantar Çorbası";
  double urunFiyati = 35000;
  String sirket = "Huawei";
  String videoAdi = "Çekiştir beni Gittiğin Yere ! İtalya";
  String muzikSuresi = "4:31";
  double mekanPuani = 4.7;
  String dosyaAdi = "odev1.dart";
  String resimFormati = "jpg";
  const String renk = "mavi";
  const String renkKodu = "#0000ff";
  String bilgisayarModeli = "Asus";
  double ekranBoyutu = 15.6;
  String kullanimSuresi = "1 ay";
  String basinc = "760mm";
  String etkinlikGunu = "Pazar";
  String odemeGunu = "Cuma";
  String yolculukCikisTarihi = "12.06.2024";
  String mahalleAdi = "Sarıköy";
  String otobusHatti = "Sarıköy - Gönen";
  int kullanilanDakika = 1500;
  String kargotakipNo = "154564845152";
  String kuponSuresi = "5 gün";
  String kuponKodu = "45484";
  String faturaTarihi = "13.05.2024";

  print("İlçe: $ilce");
  print("Kıta: $kita");
  print("Faks: $faks");
  print("Posta kodu : $postaKodu");
  print("Instagram adresi : $instaAdresi");
  print("Çalıştığın bölüm : $calistiginBolum");
  print("Ürün miktarı : $urunMiktari");
  print("Müşteri soyadı : $musteriSoyadi");
  print("Ödeme miktarı : $odemeMiktari");
  print("Doğum tarihi: $dogumTarihi");
  print("Borç : $borc");
  print("Medeni hal : $medeniHal");
  print("Video yorumu : $videoYorumu");
  print("Ödeme saati : $odemeSaati");
  print("Eft miktarı : $eftMiktari");
  print("Satılan miktar : $satilanMiktar");
  print("Telefon modeli : $telefonModeli");
  print("Dergi adı : $dergiAdi");
  print("Basım tarihi : $basimTarihi");
  print("Zam miktarı : $zamMiktari");
  print("Daire sayısı : $daireSayisi");
  print("Enlem : $enlem");
  print("Boylam : $boylam");
  print("Yemek adı : $yemekAdi");
  print("Ürün fiyatı : $urunFiyati");
  print("Şirket : $sirket");
  print("Video adı: $videoAdi");
  print("Müzik süresi : $muzikSuresi");
  print("Mekan puanı : $mekanPuani");
  print("Dosya adı: $dosyaAdi");
  print("Resim formatı: $resimFormati");
  print("Renk: $renk");
  print("Renk kodu: $renkKodu");
  print("Bilgisayar modeli: $bilgisayarModeli");
  print("Ekran boyutu: $ekranBoyutu");
  print("Kullanım süresi: $kullanimSuresi");
  print("Basınç : $basinc");
  print("Etkinlik günü : $etkinlikGunu");
  print("Ödeme günü : $odemeGunu");
  print("Yolculuk çıkış tarihi : $yolculukCikisTarihi");
  print("Mahalle adı : $mahalleAdi");
  print("Otobüs hattı : $otobusHatti");
  print("Kullanılan dakika : $kullanilanDakika");
  print("Kargo takip no : $kargotakipNo");
  print("Kupon süresi : $kuponSuresi");
  print("Kupon kodu : $kuponKodu");
  print("Fatura tarihi : $faturaTarihi");
}
